apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: employee-portal-pvc
  namespace: employee-portal-ns

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi